### ISSUE TITLE
Zookeeper image fails to start since /tmp/zookeeper already exists

### ISSUE THREAD

**Issue by svenkataraman666** [HariSekhon/Dockerfiles#1]
May be modify mkdir /tmp/zookeeper to mkdir -p /tmp/zookeeper in entry point script.

**Comment by HariSekhon** [comment]
I noticed that and thought I'd done it already but it seems I haven't, I've just pushed that change to the entrypoint. DockerHub should rebuild it given a bit of time.

Thanks for reminding me about this.
