### ISSUE TITLE
why does "curl http://localhost:8088" display empty?

### ISSUE THREAD

**Issue by jimmy-peng** [HariSekhon/Dockerfiles#11]

**Comment by HariSekhon** [comment]
Try `curl -ivv` to see more details including headers and response code and paste the result back here please.

Is it possible your docker host is not on localhost, eg. if on Mac it's often run as a VM on an internal host network with an IP of 192.168.99.100 instead.

**Comment by HariSekhon** [comment]
Any update on this?

Also you haven't mentioned which docker image you are running but I'm assuming `hadoop` or `hadoop-dev`?

**Comment by HariSekhon** [comment]
Closing for lack of feedback, please re-open if necessary.
