### ISSUE TITLE
SolrCloud: tail error

### ISSUE THREAD

**Issue by grozeille** [HariSekhon/Dockerfiles#16]
When started, it keeps saying:

```
tail: read error: Is a directory
tail: read error: Is a directory
tail: read error: Is a directory
```

The tail command is done on several folders:

`tail -f /dev/null /solr/example/cloud/node1/logs/archived /solr/example/cloud/node1/logs/solr-8983-console.log /solr/example/cloud/node1/logs/solr.log /solr/example/cloud/node1/logs/solr_gc.log.0.current /solr/example/cloud/node2/logs/archived /solr/example/cloud/node2/logs/solr-7574-console.log /solr/example/cloud/node2/logs/solr.log /solr/example/cloud/node2/logs/solr_gc.log.0.current
`

- /solr/example/cloud/node1/logs/archived
- /solr/example/cloud/node2/logs/archived

**Comment by HariSekhon** [comment]
I think you can ignore that error as superficial, if an archived directory is created we don't really want to be tailing it anyway.
