### ISSUE TITLE
How to map

### ISSUE THREAD

**Issue by ABHSY** [HariSekhon/Dockerfiles#25]
The interface can be accessed through 16301 in VMware, but not in an external environment.If the mapping allows docker's services to be mapped outside

**Comment by HariSekhon** [comment]
How to map what HBase? Standard Docker `-p` switch for mapping on the Docker host?

**Comment by ABHSY** [comment]
yeah I'm try this command docker -p .

**Comment by HariSekhon** [comment]
Glad it works for you, closing.
