### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by rajendrapatil** [HariSekhon/Dockerfiles#3]
Hey this is basically inquiry, Bit new to docker, and just trying to learn and use it. 
What I looking for is docker image or file, which will have combination of 
1. Java
2. Scala
3. Eclipse
4. Maven
5. Hadoop 

If you can help me out or share the image path with having maximum of all these in one image.

**Comment by HariSekhon** [comment]
Have you looked at ```harisekhon/hadoop-dev``` on DockerHub (the Dockerfile is in this repo).

**Comment by rajendrapatil** [comment]
Thanks for revert. I did indeed. Have gone through it, 
I may be asking too basic question at this stage, spare me :-) 
1 . Once I pull that image harisekhon/hadoop-dev, how can I see the details what does image includes? 
2. Also, just suggestion, hadoop works good independent of OS, what I believes, still if I say what's better and more compatible, cent-os or ubuntu ? currently I am planning to go with ubuntu, one liner will do.

**Comment by HariSekhon** [comment]
Look at the corresponding Dockerfile in this repo to see what the image
includes.

Redhat / CentOS are much more widely used and better supported by the
Hadoop vendors as they are what is commonly deployed in large enterprises
(as opposed to small startups with ubuntu)

-- 
Best Regards,

Hari Sekhon
https://www.linkedin.com/in/harisekhon
<http://www.linkedin.com/in/harisekhon>

**Comment by rajendrapatil** [comment]
Thanks. It answers me. 
I have taken different approach now since using ubuntu system.
I used harisekhon/centos-scala as a base image and now installing rest applications like maven and hadoop on it to make a complete package

**Comment by HariSekhon** [comment]
The hadoop-dev image already contains Hadoop as well as Java, Maven etc. Look at the FROM line for the inherited image to see what software the image inherits.
