### ISSUE TITLE
hbase2.1 in windows regionserver connection refused

### ISSUE THREAD

**Issue by zuzeep** [HariSekhon/Dockerfiles#31]
when access http://myhbase:16010/master-status is success.
but access http://myhbase:16030/rs-status show the error:
Connection Refused
[D]Connection Refused|dial tcp4 192.168.137.1:16030: getsockopt: connection refused

os: windows 10
hbase tags: 2.1

**Comment by HariSekhon** [comment]
The mappings in 2.x changed from 16301 to 16030.

I've updated the Makefile and docker-compose.yml to additionally open port 16030.

Please git pull and try again.
