### ISSUE TITLE
fstat unimplemented unsupported or native support failed to load

### ISSUE THREAD

**Issue by yh794406573** [HariSekhon/Dockerfiles#33]
NotImplementedError: fstat unimplemented unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries
  initialize at org/jruby/RubyIO.java:1013
        open at org/jruby/RubyIO.java:1154
  initialize at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/input-method.rb:141
  initialize at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/context.rb:70
  initialize at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb.rb:426
  initialize at /hbase/lib/ruby/irb/hirb.rb:47
       start at /hbase/bin/../bin/hirb.rb:181
      <main> at /hbase/bin/../bin/hirb.rb:193

**Comment by yh794406573** [comment]
docker image: harisekhon/hbase

**Comment by ruinshe** [comment]
Hi Hari,

I saw you committed a quick fix to update the tag from 2.1.0 to 2.1.1, do you have plan to push it to docker hub? I just pull the image from docker hub and checked the hbase version in the image is still 2.1.0.

Best regards,
Ruins

**Comment by ruinshe** [comment]
Update for correction: I used `docker-compose up -d` to start hbase. After I changed the `${VERSION:-latest}` to `2.1` as image tag, the hbase version becomes `2.1.1`.

**Comment by yh794406573** [comment]
> Thanks for reporting this.
> 
> Looks like an upstream library problem due to HBase shell being written in JRuby, combined with DockerHub auto-rebuilds having replaced the prior working image when upstream changed.
> 
> I've just pushed a new fixed version, please try again now.
> 
> I've also added a test protection in the docker build to catch any HBase shell breakage in future to prevent autobuild updates if something like this happens again that breaks the HBase JRuby shell.

Thanks.
