### ISSUE TITLE
Add install of package zip

### ISSUE THREAD

**Issue by disoardi** [HariSekhon/Dockerfiles#34]
I tried to build the pytools docker but I had this error:
`make spark-deps
make[4]: Entering directory '/github/pytools'
rm -vf spark-deps.zip
zip spark-deps.zip pylib
make[4]: zip: Command not found
`
I fixed this issue by adding the package zip to the apt-get install command

**Comment by HariSekhon** [comment]
I've added this back in to the pytools repo packages so it'll be included in docker builds, this doesn't show up in normal OS installs since zip is often available.
