### ISSUE TITLE
Jython: Support for mock

### ISSUE THREAD

**Issue by mmanak** [HariSekhon/Dockerfiles#35]
I need to use mock(https://pypi.org/project/mock/) with Jython. Are there any plans to include it?

**Comment by HariSekhon** [comment]
I've just pushed `harisekhon/jython-dev` which has pip, jip and mock installed as well a jython.

Give it a try.

The source is stuck behind a big change I have coming for Hadoop and HBase so I can't push it just yet until that is finished.

**Comment by mmanak** [comment]
I am not able to find "harisekhon/jython-dev" branch. Please would you be able to provide link? 

Thanks

**Comment by mmanak** [comment]
I have found this here https://hub.docker.com/r/harisekhon/jython-dev/dockerfile but would you be able to provide Dockerfile please?

**Comment by HariSekhon** [comment]
The docker image is available for use on docker hub, just pull it.

As mentioned the jython-dev Dockerfile is committed but not pushed to GitHub yet because I have a large refactoring for Hadoop and HBase underway and a push would also send commits for those before the work is finished. I will complete it any day and push the sources, but right now the docker image is available to run from DockerHub itself.

**Comment by mmanak** [comment]
Would you be able to point me to which Mock library do we have in image? Is it this one https://docs.python.org/dev/library/unittest.mock.html#module-unittest.mock or something else?

Thanks

**Comment by mmanak** [comment]
Please reply. I need to understand this as I am not able to do import unittest.mock but import mock

**Comment by HariSekhon** [comment]
I've pushed it to a jython-dev branch as it's not ready to go in to master yet.

You can see the Dockerfile here:

https://github.com/HariSekhon/Dockerfiles/blob/jython-dev/jython-dev/Dockerfile

**Comment by HariSekhon** [comment]
You might have missed the bit at the top of the unittest.mock doc which said it's only available from Python 3.3 but Jython is 2.7, so you're using the wrong version of mock.

**Comment by mmanak** [comment]
I understand `unittest.mock` is available from v3.3 only. What I actually wanted to understand is the mock installed in Dockerfile is the backport of `unittest.mock`? The one which I originally requested (https://pypi.org/project/mock/)

Thanks

**Comment by HariSekhon** [comment]
Yes I believe so since if you look at the line here it is pulling `mock` from PyPI:

https://github.com/HariSekhon/Dockerfiles/blob/jython-dev/jython-dev/Dockerfile#L35

Feel free to fork, modify and rebuild as you need though and submit a pull request.
