### ISSUE TITLE
Questions about enable_materialized_views and enable_transient_replication for cassandra

### ISSUE THREAD

**Issue by HCHCHH** [HariSekhon/Dockerfiles#36]
Thanks for providing this useful container! I have a question about two cassandra configs: `enable_materialized_views` and `enable_transient_replication.` It seems the [official document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html)
does not recommend to enable them in production but they are set to be enabled by default:

![image](https://user-images.githubusercontent.com/4555674/56547979-b8392100-6533-11e9-9347-aafdfaef4721.png)

Shall we disable them?
Thanks!

**Comment by HariSekhon** [comment]
This is a matter of opinion. I'm inclined to leave the defaults and allow the user to override the config by doing a mount of the config file location.
