### ISSUE TITLE
Drill + Zookeeper : Unable to persist configuration

### ISSUE THREAD

**Issue by error500** [HariSekhon/Dockerfiles#37]
Hello
I am running well docker-compose command in drill project but i can't find any solution to persist drill configurations.
I can modify storage plugin configuration in the drill web interface but on docker-compose down, all is lost.
Is there any solution to create a volume or any other persistance solution ?

**Comment by HariSekhon** [comment]
Just change the docker compose config to use a volume or a bind mount. You need to edit that according to your environment.

**Comment by error500** [comment]
Yes but wich folder should be bond ?
Where is stored the conf ?

**Comment by HariSekhon** [comment]
The config is under /apache-drill/conf.

If you look at the Dockerfile of where it puts the software or exec to the running container it should be easy to spot. I put things at top-level since each image is single technology and there is no point putting /usr/local in front of everything.
