### ISSUE TITLE
Change the value of hbase.regionserver.thrift.framed for security?

### ISSUE THREAD

**Issue by hh-project-config** [HariSekhon/Dockerfiles#38]
Thanks for providing this useful container. 

I have a question about one hbase config:  It seems you keep the default setting of `hbase.regionserver.thrift.framed for security` to false. 

However, The [official document](https://hbase.apache.org/book.html#hbase.regionserver.thrift.framed) recommends to set `hbase.regionserver.thrift.framed` to at least `true`, for security:  "This is the recommended transport for thrift servers and requires a similar setting on the client side. Changing this to false will select the default transport, vulnerable to DoS when malformed requests are issued due to THRIFT-601."

It is also recommended in Cloudera's [troubleshoorting page](https://www.cloudera.com/documentation/enterprise/latest/topics/cdh_ig_hbase_troubleshooting.html) to set hbase.regionserver.thrift.framed and hbase.regionserver.thrift.compact to true.

Shall we change the two settings to `true`? 
Thanks.

**Comment by HariSekhon** [comment]
I change as little as possible from the defaults, usually you will override the config in your deployment using Docker bind mounts or Kubernetes configmaps.

Considering this requires the change on the client, I'm not inclined to change anything that might break compatibility. If someone wants to change the config on the container at runtime and the client to match, then they're free to do so, it's easy to do and doesn't require modifying this image.
