### ISSUE TITLE
Can I use hbase & hadoop?

### ISSUE THREAD

**Issue by zemelLeong** [HariSekhon/Dockerfiles#40]
I want to use Hadoop yarn and Hbase pseudo-distributed.
Which docker I can use?
thanks.

**Comment by HariSekhon** [comment]
You can just tweak the hadoop and hbase entrypoints to suit your needs.

You can use them as a base in your own Dockerfile and then just replace the entrypoint commands with whatever you want to run.

I had a lot of pending Kubernetes changes along with this from earlier in the year but I haven't had time to completely test the work to put it on github.

For now the images contain the software you need, just tweak the entrypoints.
