### ISSUE TITLE
mount volume cause FileSystemVersionException

### ISSUE THREAD

**Issue by hpstory** [HariSekhon/Dockerfiles#47]
I use docker compose to start janusgraph and hbase with following code
`version: "3"
services:

    janusgraph:
        image: janusgraph/janusgraph:0.5.3
        container_name: janusgraph1
        volumes: 
            - ./importData:/opt/janusgraph/importData
            - ./remote-objects.yaml:/opt/janusgraph/conf/remote-objects.yaml
            - /opt/janusgraph/lib
            - /opt/janusgraph/ext
        environment:
            janusgraph.storage.backend: hbase
            janusgraph.storage.hostname: xxxxxxxx
            janusgraph.storage.port: 2181
            janusgraph.cache.db-cache: "true"
            janusgraph.cache.db-cache-clean-wait: 20
            janusgraph.cache.db-cache-time: 180000
            janusgraph.cache.db-cache-size: 0.5
            janusgraph.index.search.backend: elasticsearch
            janusgraph.index.search.hostname: xxxxxxxx
            index.search.port: 9200
        ports:
            - "8182:8182"
        depends_on:
            - hbase
 
    hbase:
        image: harisekhon/hbase:2.1
        container_name: hbase
        ports:
            - "2181:2181"
            - "8080:8080"
            - "8085:8085"
            - "9090:9090"
            - "9095:9095"
            - "16000:16000"
            - "16010:16010"
            - "16020:16020"
            - "16030:16030"
            - "16201:16201"
            - "16301:16301"
        volumes:
            - ./hbase-data/data:/hbase-data/data   `

then **hbase** throw Exception

`2021-07-16 09:28:08,515 INFO  [master/5748bd54b4eb:16000:becomeActiveMaster] master.ActiveMasterManager: Registered as active master=5748bd54b4eb,16000,1626427683630
2021-07-16 09:28:08,709 ERROR [master/5748bd54b4eb:16000:becomeActiveMaster] master.HMaster: Failed to become active master
org.apache.hadoop.hbase.util.FileSystemVersionException: HBase file layout needs to be upgraded. You have version null and I want version 8. Consult http://hbase.apache.org/book.html for further information about upgrading HBase. Is your hbase.rootdir valid? If so, you may need to run 'hbase hbck -fixVersionFile'.
        at org.apache.hadoop.hbase.util.FSUtils.checkVersion(FSUtils.java:446)
        at org.apache.hadoop.hbase.master.MasterFileSystem.checkRootDir(MasterFileSystem.java:271)
        at org.apache.hadoop.hbase.master.MasterFileSystem.createInitialFileSystemLayout(MasterFileSystem.java:151)
        at org.apache.hadoop.hbase.master.MasterFileSystem.<init>(MasterFileSystem.java:122)
        at org.apache.hadoop.hbase.master.HMaster.finishActiveMasterInitialization(HMaster.java:860)
        at org.apache.hadoop.hbase.master.HMaster.startActiveMasterManager(HMaster.java:2272)
        at org.apache.hadoop.hbase.master.HMaster.lambda$run$0(HMaster.java:581)
        at java.lang.Thread.run(Thread.java:748)`

When i comment out the mount code, and it return to normal. Is there anything wrong
` volumes:
            - ./hbase-data/data:/hbase-data/data`

**Comment by HariSekhon** [comment]
Looks like this is the cause.
```
HBase file layout needs to be upgraded
```
Perhaps it needs a newer version of HBase or the existing hbase data needs an upgrade?

I don't use HBase any more but feel free to submit an update to this project.
