### ISSUE TITLE
Error while running apache drill with external zookeeper

### ISSUE THREAD

**Issue by anshbansal** [HariSekhon/Dockerfiles#5]
I am trying to run apache drill image and get this 
```
docker run harisekhon/apache-drill

Running non-interactively, will not open Apache Drill shell

For Apache Drill shell start this image with 'docker run -t -i' switches

Otherwise you will need to have a separate ZooKeeper container linked (one is available from harisekhon/zookeeper) and specify:

docker run -e ZOOKEEPER_HOST=<host>:2181 supervisord -n
```

I have a zookeeper already running on my localhost so I try again 

```
docker run -e ZOOKEEPER_HOST=localhost:2181  supervisord -n harisekhon/apache-drill
Unable to find image 'supervisord:latest' locally
Pulling repository docker.io/library/supervisord
docker: Error: image library/supervisord:latest not found.
```

I thought maybe the sequence was wrong and I need to specify the image first

```
docker run  harisekhon/apache-drill -e ZOOKEEPER_HOST=localhost:2181  supervisord -n
container_linux.go:247: starting container process caused "exec: \"-e\": executable file not found in $PATH"
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"-e\\\": executable file not found in $PATH\"\n".
```

Any idea what can be done to fix this?

**Comment by HariSekhon** [comment]
Your order of arguments is wrong, please see the Makefile for a working example using local zookeeper. 

For external ZooKeeper you need to link the container running Zookeeper, not something running on the host itself, best off seeing the official Docker docs linking section.

**Comment by anshbansal** [comment]
@HariSekhon Are you referring to https://github.com/HariSekhon/Dockerfiles/blob/master/apache-drill/Makefile#L40?  

`
For external ZooKeeper you need to link the container running Zookeeper, not something running on the host itself, best off seeing the official Docker docs linking section.
`
Can you share why container is necessary? We already have a zookeeper cluster. Any examples of using with container?

**Comment by anshbansal** [comment]
Would be great if you could please share an example of how you would run it in distributed mode. If you do I can send a PR for the docs.
