### ISSUE TITLE
Maintainer is deprecated

### ISSUE THREAD

**Issue by stiliajohny** [HariSekhon/Dockerfiles#51]
Hi 

Consider removing the `MAINTAINER` instruction as it is deprecated 

https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

**Comment by HariSekhon** [comment]
Yeah I saw that, tbh I didn't really agree with it being deprecated but I guess I'll have to remove it in order for these Dockerfiles to work in some future version where it gets removed.

Thanks for raising this.

**Comment by stiliajohny** [comment]
I believe you now have to make that a label, that's prob more versatile way for declaring things in the head of the docker image 

I might be opening a PR if you are happy to merge ( it will be massive thought :D :D )
