### ISSUE TITLE
Question: Is apache drill docker image meant for a distributed mode?

### ISSUE THREAD

**Issue by anshbansal** [HariSekhon/Dockerfiles#6]
I looked at the DockerFile and it looks like it is not meant for that

https://github.com/HariSekhon/Dockerfiles/blob/master/apache-drill/entrypoint.sh#L33

If it is meant for distributed mode how do I add my own drill-override.conf for the image?

**Comment by HariSekhon** [comment]
You can create a container, cp the conf in to it and then start, see here for a similar example:

https://github.com/HariSekhon/nagios-plugins/blob/master/tests/test_nginx.sh#L61
