### ISSUE TITLE
Error in Dockerfiles/rabbitmq-cluster/rabbitmq-cluster ?

### ISSUE THREAD

**Issue by ThinkBriK** [HariSekhon/Dockerfiles#7]
Hi,

I'm using your compose for rabbitmq and ran into a little bug:

when running non RAM workers, the join_cluster fails with:
```
joining cluster via seed rabbit_manager
Error: operation join_cluster used with invalid parameter: ["rabbit@rabbit_manager", []]
``` 
And everything is working on RAM nodes.
I think it's about an extra space when running the join_cluster without $RAM set.

:+1: For your work !

**Comment by HariSekhon** [comment]
Fixed.
