### ISSUE TITLE
Mount point to store hbase data ?

### ISSUE THREAD

**Issue by talbenshabtay** [HariSekhon/Dockerfiles#8]
What is the directories i need to mount in order to store hbase data on host instead of container ?

**Comment by HariSekhon** [comment]
It should follow hbase.rootdir which defaults to ${hbase.tmp.dir}/hbase which should be /tmp/hbase.

If you want to change it add that config key to the hbase-site.xml with a different value location under the conf directory.

**Comment by HariSekhon** [comment]
Did this answer this question for you?

Shall I close this ticket?

**Comment by HariSekhon** [comment]
I'm closing this for lack of feedback. Please re-open if needed.
